### ISSUE TITLE
Proposal for torpedo programs

### ISSUE THREAD

**Issue by jonlai211** [GMaster-TorpedoTeam/check_list#1]
How about inquiring from researchers with outstanding results in the South and Central teams for better test results

**Comment by SYXiao2002** [comment]
YZY haas already :( doing those things.

**Comment by jonlai211** [comment]
btw u are more convincing in working than Mr.Y

**Comment by jonlai211** [comment]
do not forget! u are the king of tropedo!!!!!!!!
